//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bpba.EntityFramework.PaginaModelo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Inventario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Inventario()
        {
            this.Venta = new HashSet<Venta>();
        }
    
        public int id { get; set; }
        public bool disponible { get; set; }
        public decimal precio { get; set; }
        public int ciudad { get; set; }
        public int Usuario_id { get; set; }
        public int Articulo_id { get; set; }
        public byte pais { get; set; }
    
        internal virtual Usuario Usuario { get; set; }
        internal virtual Articulo Articulo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        internal virtual ICollection<Venta> Venta { get; set; }
    }
}
