//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bpba.EntityFramework.PaginaModelo.EntityModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    internal partial class paginaEntities : DbContext
    {
        public paginaEntities()
            : base("name=paginaEntities")
        {
            this.Configuration.LazyLoadingEnabled = false;
            Personas = Set<Persona>();
            Usuarios = Set<Usuario>();
            Sesiones = Set<Sesion>();
            Perfiles = Set<Perfil>();
            Articulos = Set<Articulo>();
            Inventarios = Set<Inventario>();
            Ventas = Set<Venta>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        internal virtual DbSet<Persona> Personas { get; set; }
        internal virtual DbSet<Usuario> Usuarios { get; set; }
        internal virtual DbSet<Sesion> Sesiones { get; set; }
        internal virtual DbSet<Perfil> Perfiles { get; set; }
        internal virtual DbSet<Articulo> Articulos { get; set; }
        internal virtual DbSet<Inventario> Inventarios { get; set; }
        internal virtual DbSet<Venta> Ventas { get; set; }
    }
}
