//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bpba.EntityFramework.PaginaModelo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Perfil
    {
        public int id { get; set; }
        public byte acceso { get; set; }
        public string descripcion { get; set; }
        public int Usuario_id { get; set; }
    
        internal virtual Usuario Usuario { get; set; }
    }
}
