//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bpba.EntityFramework.PaginaModelo.EntityModel
{
    using System;
    using System.Collections.Generic;
    
    internal partial class Venta
    {
        public int id { get; set; }
        public System.DateTime fecha { get; set; }
        public int Inventario_id { get; set; }
        public int comprador_id { get; set; }
        public byte status { get; set; }
    
        internal virtual Inventario Inventario { get; set; }
    }
}
